# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build PR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build
      run: |
        runestone build
    - name: Publish generated content to GitHub Pages
      if: github.ref == 'master'
      uses: peaceiris/actions-gh-pages@v3
      with:
          publish_dir: build/PyZombis/
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Save PR number
      if: github.ref != 'master'
      run: |
        echo ${{ github.event.number }} > ./build/PyZombis/NR
    - name: Upload generated content artifact
      uses: actions/upload-artifact@v2
      with:
        name: website-output
        path: build/PyZombis/