# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test PR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:

    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install playwright & browsers
      run: |
        playwright install
    - name: Download generated content artifact
      uses: actions/download-artifact@v2
      with:
        name: website-output
        path: build/PyZombis/
    - name: Serve website locally
      run: |
        runestone serve &
    - name: PyTest
      run: |
        pytest --html=report.html --self-contained-html
    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: report.html
        path: report.html
    - name: Upload test videos
      uses: actions/upload-artifact@v2
      with:
        name: videos
        path: videos
